### ISSUE TITLE
Navigation sidebar scrolling scales with its size

### ISSUE THREAD

**Issue by QuLogic** [hotdoc/hotdoc_bootstrap_theme#16]
**Note**: I'm using GStreamer docs as an example here, but I believe this problem occurs in all hotdoc users since they all source the navigation scrolling from here. GStreamer docs also have the longest navigation sidebar I could find.

On the [GStreamer Application Development Manual](https://gstreamer.freedesktop.org/documentation/application-development/index.html), the navigation sidebar is initially short enough to not have a scrollbar on my display.

![Screenshot from 2022-04-08 02-42-01](https://user-images.githubusercontent.com/302469/162379222-e9e441f5-3e3a-4bd9-9ee8-f2c1b0112396.png)

I then open the Tutorials section, and every tutorial subsection, so that I have a scrollbar on the navigation sidebar. With my mouse hovering over the first element (Installing GStreamer), I scroll one notch and end up between Basic tutorial 2 and 3, which is 4.5 elements down.

![small](https://user-images.githubusercontent.com/302469/162387435-e6eb0bdf-5e53-4651-991b-43c41c7fad0f.gif)

If I then open the Plugins section at the bottom (which adds _several_ elements), start at the top, and scroll one notch, I end up between Android Tutorials and Android tutorial 1, which is 28.5 elements down.

![big](https://user-images.githubusercontent.com/302469/162387491-bb213044-9bc8-4114-b1a3-c7f877f43961.gif)

That should not happen. Scrolling should always be by the configured number of lines in the browser. Or if that can't be queried from JavaScript, then it should at least be a consistent height.

This test was done Firefox 98. In Chromium, a similar thing occurs, though the size of increase is a bit smaller, going from 2 elements to 12.5 elements.

**Comment by MathieuDuponchelle** [comment]
Ah, that's an interesting remark, to be honest I just let the default behavior occur, when you say "it should" is there some sort of actual guidelines you're referring to? I'm not a web developer by trade fwiw :)

**Comment by QuLogic** [comment]
I've found a few more sites that probably explain this better, just search for 'scrolljacking' or 'scroll hijacking'; it's mostly a problem of usability, but I think even more strongly, it's poor for accessibility: https://webflow.com/accessibility/checklist/task/avoid-scrolljacking

**Comment by ferdnyc** [comment]
Was this subsequently addressed? Because, I can't reproduce. (Trying at the GStreamer manual site linked in the first comment, using Google Chrome 118 Linux.) The sidebar scrolls the same distance using my mousewheel, regardless of its current height. When clicking on a sidebar item, if the sidebar is longer than the page, it _will_ jump that item to the top of the page — which can be a bit disconcerting, TBH — but it doesn't affect manual scrolling, at least for me.

The only commit I see regarding scrolling is 07e907e, "disable scroll inertia"... and that was in 2017, so I doubt it's relevant unless GStreamer were still using a _really_ outdated version of hotdoc all the way through 2022.

**Comment by MathieuDuponchelle** [comment]
oh, yes @ferdnyc , this was addressed with https://github.com/hotdoc/hotdoc_bootstrap_theme/commit/02837d4a27c5ee3025b4d0fc375c23f48b785d44, good call
